#!/bin/bash

# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2025 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

BOLT_LAYER_SETUP_SCRIPT=$(realpath -se "${BASH_SOURCE[0]}")

# Source main bolt setup-environment first
source "${BOLT_LAYER_SETUP_SCRIPT%/*}/../meta-bolt-distro/setup-environment"

backend_setup() {
  local layer="${1}"
  local parent="${layer}/../.."
  parent=$(readlink -m "${parent}")

  # Clone RDK layers if not present (alongside meta-bolt-distro)
  if [ ! -d "${parent}/meta-rdk-video" ]; then
    echo "Cloning meta-rdk-video..."
    git clone -b wpe_webkit_vs_firebolt https://github.com/rdkcentral/meta-rdk-video.git "${parent}/meta-rdk-video"
  fi
  for rdk_layer in meta-rdk meta-rdk-oss-reference meta-rdk-auxiliary; do
    if [ ! -d "${parent}/${rdk_layer}" ]; then
      echo "Cloning ${rdk_layer}..."
      git clone -b develop https://github.com/rdkcentral/${rdk_layer}.git "${parent}/${rdk_layer}"
    fi
  done

  # Add RDK layers to bblayers.conf
  for rdk_layer in meta-rdk meta-rdk-video meta-rdk-oss-reference meta-rdk-auxiliary; do
    local rdk_layer_path=$(readlink -m "${parent}/${rdk_layer}")
    if [ -d "${rdk_layer_path}" ] && ! grep -qs "${rdk_layer_path}" conf/bblayers.conf; then
      echo "BBLAYERS:append = \" ${rdk_layer_path}\"" >> conf/bblayers.conf
    fi
  done

  # Add bolt-backend config to local.conf (only once)
  if ! grep -qs "BEGIN meta-bolt-wpewebkit-runtime" conf/local.conf; then
    cat >> conf/local.conf << 'BOLTBACKEND'

# --- BEGIN meta-bolt-wpewebkit-runtime ---

# BBMASK - only allow needed recipes from RDK layers
BBMASK .= "|.meta-rdk/recipes-.*/(?!(wpe-backend-rdk|breakpad_wrapper|breakpad-wrapper)).*"
BBMASK .= "|.meta-rdk-video/recipes-.*/(?!(wpe-webkit|rdkat|tts|images)).*"
BBMASK .= "|.meta-rdk-oss-reference/recipes-.*/(?!(woff2|libwpe|breakpad|libepoxy)).*"

# CMF variables needed by meta-rdk-video recipes
CMF_GITHUB_ROOT = "git://github.com/rdkcentral"
CMF_GITHUB_PROTOCOL = "https"
CMF_GITHUB_BRANCH = "nobranch=1"
CMF_GITHUB_SRC_URI_SUFFIX = "protocol=${CMF_GITHUB_PROTOCOL};${CMF_GITHUB_BRANCH}"

# Distro features
DISTRO_FEATURES:append = " enable_libsoup3 opengl wayland"

# Package config
PACKAGECONFIG:remove:pn-gstreamer1.0-plugins-bad = "gl"
PREFERRED_VERSION_wpe-webkit = "2.46%"
PREFERRED_VERSION_libwpe = "1.16.2"

# MIDDLEWARE_ARCH not defined in bolt
MIDDLEWARE_ARCH = "${MACHINE_ARCH}"

# --- END meta-bolt-wpewebkit-runtime ---
BOLTBACKEND
  fi
}

bolt_layer_setup "${BOLT_LAYER_SETUP_SCRIPT%/*}" backend_setup

unset BOLT_LAYER_SETUP_SCRIPT
